apiVersion: v1
kind: Pod
metadata:
  name: loop-222
spec:
  containers:
  - name: loop
    image: busybox
    command: ["/bin/sh"]
    args: ["-c", "for i in $(seq 1 10); do echo Welcome \"$i\" times; done"]
  restartPolicy: Never

