apiVersion: v1
kind: Pod
metadata:
  name: pod-1
  labels: 
    tier: frontend
    team: artemidis
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-2
  labels: 
    tier: backend
    team: artemidis
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-3
  labels: 
    tier: backend
    team: artemidis
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
