apiVersion: v1
kind: Pod
metadata:
  name: web-server 
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
    startupProbe:
      httpGet:
        path: /
        port: 80
    readinessProbe:
      httpGet:
        path: /
        port: 80    
      initialDelaySeconds: 5
  restartPolicy: Never
