apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: replica-pods
        image: grand-server:1.4.6
        ports:
        - containerPort: 80

