apiVersion: v1
kind: Pod
metadata:
  name: frontend
  labels:
    tier: frontend
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: backend
  labels:
    tier: backend
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: ClusterIP
  selector:
    tier: backend
    app: nginx
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 80
